create table history.core_server_node (
    id BIGINT PRIMARY KEY,
		server_node_id BIGINT ,
		server_node_type_id BIGINT ,
		hostname VARCHAR(255)  not null,
		ip_address VARCHAR(255)  not null,
		port INTEGER  not null,
		username VARCHAR(255) ,
		url VARCHAR(255) ,
		user_domain VARCHAR(255) ,
		os_name VARCHAR(255) ,
		os_version VARCHAR(255) ,
		architecture VARCHAR(255) ,
		registered_at TIMESTAMP ,
		server_node_status_id BIGINT ,
		is_active integer ,
		created_by varchar(50) ,
		last_updated timestamp ,
		last_updated_by varchar(50) ,
		version integer 
);