
SET NOCOUNT ON;
SET ANSI_WARNINGS OFF;
SET ANSI_PADDING OFF;
SET QUOTED_IDENTIFIER OFF;
USE [defarge];
GO
CREATE SCHEMA history; 
GO
CREATE TABLE history.log (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    level VARCHAR(50) NOT NULL,
    principalname VARCHAR(50) NOT NULL,
    program TEXT NOT NULL,
    filepath TEXT NOT NULL,
    linenumber INTEGER NOT NULL,
    membername TEXT NOT NULL,
    message TEXT NOT NULL
  
);